### ISSUE TITLE
Consider removing the pending queue

### ISSUE THREAD

**Issue by ivan** [ArchiveTeam/ArchiveBot#109]
When there are no pipeline slots available for a job, ArchiveBot currently puts the job in the pending queue and starts the job immediately after a pipeline can serve an additional job.

This behavior is a problem because new jobs often require the attention of someone who will add ignores.  Not all ignores can be predicted in advance, nor are users usually even willing to try.  The current behavior frequently starts a job when the submitter, and perhaps no one else, is paying any attention to the dashboard.

An alternative to the pending queue is to reject an `!a` if there are no pipelines available to serve it.  This will ensure that whenever a job starts, the submitter is around to add ignores.

If we have no backlog of jobs because there is enough pipeline capacity, everything works the same as before.

But we may have large backlogs of jobs in the future.  To deal with these, we could use https://etherpad.mozilla.org/ to organize a list of sites we want to crawl.  Whenever a pipeline has some capacity, we can `!a` the first URL on the list and remove it from the etherpad.  Whoever actually starts the job makes the implicit promise of adding some ignores if necessary.  Another advantage of the etherpad: we can rearrange the queue (currently, we can't do this.)

**Comment by ivan** [comment]
The bot in #archivebot is now patched to reject new jobs if there's anything already in the queue, but this seems like a feature that needs to be configurable for other users of ArchiveBot.

**Comment by falconkirtaran** [comment]
I'm not sure this is still a good idea.  We have lots of capacity and it's somewhat rare for anything to be in the queue, and using an etherpad seems to present an additional failure mode.  It's possible to rearrange queues in Redis, but it hasn't crossed my mind to do so ever.

**Comment by yipdw** [comment]
I've removed the queue check on the `#archivebot` bot; we'll see how things work out.

**Comment by ivan** [comment]
I am closing this because \#archivebot seems to be happy with #337.
