### ISSUE TITLE
Favicon doesn't appear on archivebot.com

### ISSUE THREAD

**Issue by PressStartandSelect** [ArchiveTeam/ArchiveBot#127]
The dashboard's favicon only shows on http://arshboard.at.ninjawedding.org:4567, but does not show on http://archivebot.com. A minor issue, but ideally it should show on both.

**Comment by ivan** [comment]
Framebusting is now implemented in dashboard 2.0

**Comment by ivan** [comment]
You can't stay on archivebot.com now, so this is "fixed" ;)
