### ISSUE TITLE
AT&T wifi interstitial does not cause pipeline "good to go" checks to fail

### ISSUE THREAD

**Issue by yipdw** [ArchiveTeam/ArchiveBot#158]
Some Starbucks and other cafe-like stores use an AT&T wifi setup that forces users to click an "Accept and Connect" button to begin accessing the Web.  Until this button is pressed, all HTTP requests will be given the interstitial.  (Not sure what happens on HTTPS.)

The CheckIP task does not fail in the online-but-have-not-clicked-the-button case.  I'm not sure if that's within its scope (it's called CheckIP, after all, not CheckContent or whatever).

It's probably not a good idea to run an ArchiveBot pipeline on coffee shop wifi.  However, this problem can manifest in other ways.

**Comment by yipdw** [comment]
This might belong in ArchiveTeam/seesaw-kit's tracker, but CheckIP is defined in ArchiveBot's pipeline.  Feel free to move, however.

A known endpoint with known content (`tracker.archiveteam.org/check`, maybe) is a direct way to check this.

**Comment by chfoo** [comment]
See ArchiveTeam/seesaw-kit#28, @12As essentially wrote out a spec.

**Comment by yipdw** [comment]
Oops, I forgot that that issue existed.  Closing this one.
