### ISSUE TITLE
Idea: Russian MediaWiki ignore set?

### ISSUE THREAD

**Issue by ethus3h** [ArchiveTeam/ArchiveBot#191]
I think this might be right, but is line 8 too long?

Also why the .... can't I upload a json file to github? People using this site tend to use programming-type files a lot, I suspect... Duh. (this would need to be renamed to json because of that.)

[(2015-11-21n8) mediawikiru.txt](https://github.com/ArchiveTeam/ArchiveBot/files/40975/2015-11-21n8.mediawikiru.txt)

**Comment by yipdw** [comment]
It's easier to review a pull request than an upload; please re-file this as a PR.  (I don't know if Github still has the convert-issue-to-pull-request function.)

Also, is this a reason for this to not be part of the existing Mediawiki set?

**Comment by ethus3h** [comment]
Voila https://github.com/ArchiveTeam/ArchiveBot/pull/192
