### ISSUE TITLE
If a URL contains a %s the dashboard can't interact with it

### ISSUE THREAD

**Issue by tylerknott** [ArchiveTeam/ArchiveBot#211]
For example if a job downloads the URL https://media2.wnyc.org/i/%s/%s/%s/%s/1/toddheadshot.jpg you won't be able to click the link to open the URL in the browser or access any of the right-click menu options (the right-click menu appears to open but with no options available).

**Comment by ivan** [comment]
I can't reproduce this now. I tested the non-beta dashboard in the latest stable Chrome and Firefox on Windows 10 with some `url = "https://media2.wnyc.org/i/%s/%s/%s/%s/1/toddheadshot.jpg";` added in `getSuggestedCommands`.

If you still see this, please let me know your browser and what errors you see in the browser's DevTools console.
