### ISSUE TITLE
Update Phatomjs to latest version 2.1.1

### ISSUE THREAD

**Issue by luckcolors** [ArchiveTeam/ArchiveBot#213]
Hello.
I'm trying to install phantomjs version 1.9.8 but it has problems compiling.
However compiling 2.1.1 didn't give any problems and was as easy as apt install and python build.py.
it would be great if the version could be updated.
Thanks in advance.

**Comment by yipdw** [comment]
The main reason we didn't go from PhantomJS 1.9.8 to 2 is because I'm not sure if the control interface is the same.  A project changing major versions is often their "hey we broke something important" signal.

**Comment by luckcolors** [comment]
My pipeline is currently equipped with that version (currently setted with archive only=1).
So it can probably be a test to see if it does work i suppose.
