### ISSUE TITLE
Error during crawl: ssl.SSLEOFError: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by luckcolors** [ArchiveTeam/ArchiveBot#214]
Here's the log: http://paste.harrycross.me/view/0e2b296a
This error doesn't crash the archival, it sometimes happens for certains url.
Seems to affect different pipelines.

**Comment by yipdw** [comment]
If the crawl continues, I don't think this is harmful.  

The trace looks like a TLS misconfiguration and/or misbehavior on the site being archived.
