### ISSUE TITLE
Can't unignore ignore patterns that are too long

### ISSUE THREAD

**Issue by tylerknott** [ArchiveTeam/ArchiveBot#218]
I put in an ignore pattern that was split between two messages and so the bot only picked up the first part (which was invalid by itself). Then, when I went to ungiore it the !unig command is two characters longer than the !ig command so the pattern could not be unignored.  Please add another alias for unignoring like !ug so this will not be a problem.

**Comment by JustAnotherArchivist** [comment]
Fixed by #287 over a year ago.
