### ISSUE TITLE
Job hanging bug/Upgrade to wpull 2.0

### ISSUE THREAD

**Issue by Frogging101** [ArchiveTeam/ArchiveBot#219]
Currently there is a bug in some part of ArchiveBot that causes jobs to hang when they are near completion, with a small number (`concurrency` or less) of URLs remaining in the queue. When this happens, strace will show `epoll_wait` waiting forever either with an infinite timeout, as reported by FalconK, or an infinite number of ~20 second timeouts. Poking at it with gdb produced mostly inconclusive results for various reasons, but the stack traces I saw lead me to believe that it is a trollius bug (likely in its EpollSelector code, which directly manipulates epoll).

As I understand it, wpull 2.0 has replaced trollius with Python 3's native asyncio. If this problem is caused by trollius, then it may well be fixed by upgrading wpull to version 2.0.

@chfoo, as someone very familiar with both ArchiveBot and wpull, do you have any input?

**Comment by chfoo** [comment]
I plan to rewrite the hook script to support Wpull 2.0 some time in the future.

**Comment by yipdw** [comment]
We've been on wpull 2 for a while, and it _seems_ like the job hanging bug has been squashed with it.  Yes? No?

**Comment by falconkirtaran** [comment]
I haven't seen it since.
