### ISSUE TITLE
ArchiveBot doesn't fully get Javascript-generated URL 

### ISSUE THREAD

**Issue by DoomTay** [ArchiveTeam/ArchiveBot#222]
If I sic ArchiveBot on a page like http://www.iridion2.com/worldranking/arcade2.html and it it goes after, say, `<a href="javascript:profile(556)" title="Show BENI BROS's profile">BENI BROS</a>`, then I expect the URL it follows to be `http://www.iridion2.com/worldranking/profile556.html`. But I noticed from the log that it will try `http://www.iridion2.com/worldranking/profile` and of course fail.

**Comment by yipdw** [comment]
ArchiveBot does not use its own heuristics for this sort of thing; it uses wpull's Javascript heuristics, which in turn are derived from wget's.  Please file a wpull issue.

Alternatively, you may want to try using PhantomJS mode.
