### ISSUE TITLE
!explain and !ex should be able to be invoked by an IRC user who does not have voice or ops

### ISSUE THREAD

**Issue by Asparagirl** [ArchiveTeam/ArchiveBot#223]
Right now, a non-voiced/non-ops IRC user can still use !ao to start a grab of a specific page.  But if they then want to add an explanation or warning to their grab, they can't.

**Comment by ethus3h** [comment]
(Bear in mind that users without voice or ops could conceivably use !ex to maliciously change the !ex set by another user, unless that were prevented.)

**Comment by falconkirtaran** [comment]
If we did this, we'd need to also enforce that it's their job I think, but this comes up basically never.  It'd certainly be nicer if it worked this way though.

**Comment by C4K3** [comment]
This also prevents a non-voiced user from using --explain in !ao, in which case you get the following:
```
!ao <url> --explain "<explanation>
Queued <url> for archival without recursion.
Use !status <ident> for updates, !abort <ident> to abort.
Sorry, only channel operators or voiced users may use that command.
```
Where the job is started properly, but the explanation is not added.

**Comment by Flashfire42** [comment]
If there is a way to make it so for non-voiced that use explain only that user who queued the job can edit the explain (Except for opped or voiced users that it)

**Comment by JustAnotherArchivist** [comment]
That would mean having to implement some sort of join/leave/netsplit tracking into the IRC bot, which would add a lot of complexity. And as @falconkirtaran mentioned, the issue comes up only rarely, in particular since most `!ao` jobs are small and often don't need an explanation to begin with. So I don't think it's worth doing that. However, `--explain` should definitely be supported, and that should be quite trivial to fix.

**Comment by JustAnotherArchivist** [comment]
#357 will fix the issue of unvoiced users not being able to use `--explain`. As mentioned, adding support for `!explain` is much more complex due to the connection tracking, and the time and effort needed for that is better invested in other, more common and problematic issues.
