### ISSUE TITLE
Content-lenght-timeout should not happen if the server returns the total file lenght.

### ISSUE THREAD

**Issue by luckcolors** [ArchiveTeam/ArchiveBot#225]
Currently it may happen when getting a 30gb file with Archivebot that the file currently in download may  run into content-lenght-timeout, this should not happen if the server does provide the content lenght.
This would of course still prevent archivebot from endlessy getting for example an infinite radio stream but it would make those big file download correctly. Probably having a switch to enable this feature on jobs with bigfiles would be a good idea.

**Comment by yipdw** [comment]
Stream detection is already in place; see e.g. https://github.com/ArchiveTeam/ArchiveBot/blob/master/pipeline/wpull_hooks.py#L223.  If you're running into a new sort of stream, we need to know what that is.
