### ISSUE TITLE
Dashboard should show an estimate of how long it will take for a job to finish

### ISSUE THREAD

**Issue by DoomTay** [ArchiveTeam/ArchiveBot#229]
So if there are 1,213,243 items and the job goes at ~6.1 per second, then the dashboard would show an estimated completion time of approximately 2 days and 7 hours

**Comment by chronomex** [comment]
How exactly would this estimate be computed?  Remember, the queue tends to grow continuously and taper off.

**Comment by DoomTay** [comment]
It could be computed by dividing the known queue by the shown rate. Yes, the estimation would fluctuate a bit, but then again, Windows is infamous for that same thing.

**Comment by yipdw** [comment]
Is a bad estimate better than no estimate?  I think it's better to only present the known data.

There have been some experiments in using the dashboard data to build graphs (and, from there, trends), see e.g. https://wiki.dequis.org/notes/archivebot_dashboard_fun/.  You might find that to be a good starting point for extending one of the existing dashboards or making a separate tool.
