### ISSUE TITLE
Increase maximum size for pipeline names, and/or add a new error message for pipeline name length

### ISSUE THREAD

**Issue by Asparagirl** [ArchiveTeam/ArchiveBot#274]
Attempting to name a pipeline archiveteam-has-its-eyes-on-you wouldn't work, it kept telling me pipeline names had to only have letters, numbers, or hyphens.  But after retyping over and over, I finally figured out that the actual problem was that the name was just too long.  Either we should allow longer pipeline names or else we should have a dedicated error message for exceeding the maximum length, maybe both.

**Comment by JustAnotherArchivist** [comment]
This is a limitation in seesaw. Specifically, it checks whether the downloader nickname – which is used as the pipeline name in the context of ArchiveBot – matches `^[-_a-zA-Z0-9]{3,30}$`. ArchiveBot itself doesn't care about the length as far as I know.

Closing since this is not fixable in AB.
