### ISSUE TITLE
Uploader script should check whether RSYNC_URL ends with a slash

### ISSUE THREAD

**Issue by JustAnotherArchivist** [ArchiveTeam/ArchiveBot#305]
I discovered today that one of the pipelines had been uploading files named `a` to FOS. The cause of this was that the environment variable `RSYNC_URL` had a typo and was set to `rsync://fos.textfiles.com/archivebot/a`. Each file that was moved to `~/warcs4fos` was then uploaded to FOS as `a`, overwriting the previous file (as far as I can tell).

`uploader.py` should check whether `RSYNC_URL` ends in a slash to avoid this. If there is no slash at the end, it should *at the very least* print a big, fat warning. But probably it should just fail, since I have a hard time coming up with any scenario where such a URL would actually be wanted.

**Comment by Iggersm00** [comment]
Pull #308 should cover this going forward

**Comment by JustAnotherArchivist** [comment]
Fixed by #382
