### ISSUE TITLE
Add a version check for wpull to pipeline.py

### ISSUE THREAD

**Issue by JustAnotherArchivist** [ArchiveTeam/ArchiveBot#306]
As it turned out, several pipelines have been using the original wpull release (version 2.0.1) instead of @falconkirtaran's fork (version 2.0.3). This has been causing a lot of issues (crashes, full disks, and odd network errors). `pipeline.py` should check whether `wpull.version.__version__ == '2.0.3'` to avoid this in the future.

**Comment by Iggersm00** [comment]
https://github.com/ArchiveTeam/ArchiveBot/pull/307

Created pull request with this fix

**Comment by JustAnotherArchivist** [comment]
Thanks!

#307 got merged, so I'm closing this.
