### ISSUE TITLE
Automatically abort jobs when available disk space passes some threshold

### ISSUE THREAD

**Issue by yipdw** [ArchiveTeam/ArchiveBot#32]
If a job's available disk space exceeds some threshold, it should abort itself.

"Abort", in this context, means the same thing it does in the rest of ArchiveBot: immediately terminate grab, upload the partial result, and inform the bot's task tracker.

**Comment by chfoo** [comment]
Wpull supports monitoring space and memory and the options to use them were committed in f6dba192689c741f3959778c2e25f56faf6515c9. I think the remaining work left is to determine what values to use.

**Comment by falconkirtaran** [comment]
I think the wpull threshold functionality fills the requirement here.
