### ISSUE TITLE
How to request archive of a small website?

### ISSUE THREAD

**Issue by w4rner** [ArchiveTeam/ArchiveBot#466]
My first time in an IRC channel:
![image](https://user-images.githubusercontent.com/31451410/93746552-39935800-fbed-11ea-8b21-1d041b827f94.png)
I did read the docs for the command (https://archivebot.readthedocs.io/en/latest/commands.html#archive) but looks like I need help from an admin.

**Comment by w4rner** [comment]
![image](https://user-images.githubusercontent.com/31451410/93746646-634c7f00-fbed-11ea-8ae0-83b2e05c24e9.png)

**Comment by JustAnotherArchivist** [comment]
Yeah, the archival commands are restricted to prevent abuse. Just come to \#archivebot, mention the target site and the reason for archival, and wait for someone to respond. That might take a bit depending on whether someone's around. Also, if your message gets drowned in the bot noise, don't be afraid of repeating your suggestion.

**Comment by JustAnotherArchivist** [comment]
I'm closing this issue as you managed to come there today, but feel free to ask if you have any further questions.
