### ISSUE TITLE
Add Discord assets to global ignoreset

### ISSUE THREAD

**Issue by Sanqui** [ArchiveTeam/ArchiveBot#518]
`^https://discord\.com/assets/`

100s of urls that waste time and resources because they probably get captured on cursory crawls anyway.

![image](https://user-images.githubusercontent.com/289437/126982929-24cdab9e-b8bf-4118-927d-cb3b986dedb5.png)

**Comment by tomodachi94** [comment]
@Sanqui is this on websites with the Discord widget? Just curious.

**Comment by tomodachi94** [comment]
Also, looks like this was fixed in 63118fa1d65f11390fcb1d0ab9a40e221566f3c9

**Comment by Sanqui** [comment]
It was a problem also on websites with just a link to a Discord invite (when ArchiveBot was run with offsite links, which is the default).  But yeah I got my way in 63118fa1d65f11390fcb1d0ab9a40e221566f3c9.
