### ISSUE TITLE
Add support for Amazon S3 Bucket list .xml files

### ISSUE THREAD

**Issue by upintheairsheep** [ArchiveTeam/ArchiveBot#527]
http://cds.p6v7v3q9.hwcdn.net/

**Comment by JustAnotherArchivist** [comment]
That's an S3-style bucket listing, not really a sitemap. It's not supported by ArchiveBot or wpull.

**Comment by upintheairsheep** [comment]
Can you add support for it or at least make a script to turn this into a list of urls?
