### ISSUE TITLE
Sort queue by number of pages the site has, according to Google Search

### ISSUE THREAD

**Issue by ivan** [ArchiveTeam/ArchiveBot#73]
e.g.

```
!a http://www.cnn.com/
```

results in a `site:http://www.cnn.com/` query that indicates 671,000 results, and thus the site should be crawled after sites with a smaller number of pages.

**Comment by yipdw** [comment]
We're not really using a queue anymore; is this issue still relevant?

**Comment by ivan** [comment]
Nope
