### ISSUE TITLE
Also run youtubedown on Youtube URLs

### ISSUE THREAD

**Issue by yipdw** [ArchiveTeam/ArchiveBot#82]
Youtubedown: http://www.jwz.org/hacks/youtubedown

(archived copy: http://web.archive.org/web/20140703135646/http://www.jwz.org/hacks/youtubedown)

When ArchiveBot gets a youtube.com or youtu.be URL, it should also run youtubedown and shove the results in the generated WARC.

**Comment by matthazinski** [comment]
Perhaps this tool is appropriate? https://github.com/matthazinski/youtube2internetarchive

**Comment by yipdw** [comment]
The `youtube-dl` branch now seems to mostly work.  Here are two examples done with wpull 1.2 and youtube-dl 2015.05.10.

- http://archivebot-prod3.at.ninjawedding.org/main/20150511080806/https://www.youtube.com/watch?v=jNQXAC9IVRw ("Me at the zoo"; might as well archive video one.)
- http://archivebot-prod3.at.ninjawedding.org/main/20150511074734/https://www.youtube.com/watch?v=YxAnInysd3o (a 720p source, just to demonstrate that we can get some reasonable quality -- I need to try 1080p+.  Success in that, of course, is dependent on youtube-dl version and however Youtube breaks stuff that particular day.)
  
You may initially see the "error loading video" screen; this is fine.  It'll take some time for the video to load.

There are at least two remaining things to solve before this goes to master:

```
[03:04:30] <yipdw> - the default youtube-dl mode runs into TLS cert errors in my Ubuntu VM.  this can addressed with a youtube-dl config but I'd like to write a wpull patch that passes no-check-certificate if wpull is set to not check certs
[03:04:42] <yipdw> - --youtube-dl with !a jobs is likely to bring misery
[03:04:54] <yipdw> not sure if that should be outright banned or what; I can see it being useful but asdklfdjfsdf
```

**Comment by Asparagirl** [comment]
\o/
